version: "3.8"

services:
  fc-club-stats-prod:
    build:
      context: .
      target: production
    container_name: fc-club-stats
    stdin_open: true
    tty: true
    # ports:
      # - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped